<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-J5QL42J" failures="4" tests="11" name="Default test" time="0.898" errors="0" timestamp="2022-04-15T16:01:55 ICT">
  <testcase classname="com.source.dao.test.NhanVienDAOTest" name="deleteTest" time="0.595"/>
  <testcase classname="com.source.dao.test.NhanVienDAOTest" name="deleteTest2" time="0.041"/>
  <testcase classname="com.source.dao.test.NhanVienDAOTest" name="f" time="0.002"/>
  <testcase classname="com.source.dao.test.NhanVienDAOTest" name="f" time="0.002"/>
  <testcase classname="com.source.dao.test.NhanVienDAOTest" name="insertTest2" time="0.002">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.source.model.NhanVien.getMaNV()&amp;quot; because &amp;quot;entity&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.source.model.NhanVien.getMaNV()" because "entity" is null
at com.source.dao.NhanVienDAO.insert(NhanVienDAO.java:34)
at com.source.dao.test.NhanVienDAOTest.insertTest2(NhanVienDAOTest.java:132)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- insertTest2 -->
  <testcase classname="com.source.dao.test.NhanVienDAOTest" name="selectAllTest" time="0.072">
    <failure type="java.lang.AssertionError" message="Collections not equal: expected: null and actual: [Hoàng Văn Tú, Dương Thanh Phương, Nguyễn Thế Thọ, Trần Văn Phú, Hoàng Văn A, Nguyễn Thị Hoàng, Dương Quốc Huy, Hồ Hoàng Phú, Nguyễn Thị Kim Ngân, Trần Thị Kim Dung, Trần Đức Quang]">
      <![CDATA[java.lang.AssertionError: Collections not equal: expected: null and actual: [Hoàng Văn Tú, Dương Thanh Phương, Nguyễn Thế Thọ, Trần Văn Phú, Hoàng Văn A, Nguyễn Thị Hoàng, Dương Quốc Huy, Hồ Hoàng Phú, Nguyễn Thị Kim Ngân, Trần Thị Kim Dung, Trần Đức Quang]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.assertEquals(Assert.java:1085)
at org.testng.Assert.assertEquals(Assert.java:1065)
at com.source.dao.test.NhanVienDAOTest.selectAllTest(NhanVienDAOTest.java:81)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- selectAllTest -->
  <testcase classname="com.source.dao.test.NhanVienDAOTest" name="selectAllTest2" time="0.031">
    <failure type="java.lang.AssertionError" message="Collections not equal: expected: null and actual: [Hoàng Văn Tú, Dương Thanh Phương, Nguyễn Thế Thọ, Trần Văn Phú, Hoàng Văn A, Nguyễn Thị Hoàng, Dương Quốc Huy, Hồ Hoàng Phú, Nguyễn Thị Kim Ngân, Trần Thị Kim Dung, Trần Đức Quang]">
      <![CDATA[java.lang.AssertionError: Collections not equal: expected: null and actual: [Hoàng Văn Tú, Dương Thanh Phương, Nguyễn Thế Thọ, Trần Văn Phú, Hoàng Văn A, Nguyễn Thị Hoàng, Dương Quốc Huy, Hồ Hoàng Phú, Nguyễn Thị Kim Ngân, Trần Thị Kim Dung, Trần Đức Quang]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.assertEquals(Assert.java:1085)
at org.testng.Assert.assertEquals(Assert.java:1065)
at com.source.dao.test.NhanVienDAOTest.selectAllTest2(NhanVienDAOTest.java:143)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- selectAllTest2 -->
  <testcase classname="com.source.dao.test.NhanVienDAOTest" name="selectByIdTest" time="0.031"/>
  <testcase classname="com.source.dao.test.NhanVienDAOTest" name="selectByIdTest2" time="0.032"/>
  <testcase classname="com.source.dao.test.NhanVienDAOTest" name="updateTest" time="0.002"/>
  <testcase classname="com.source.dao.test.NhanVienDAOTest" name="updateTest2" time="0.002">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.source.model.NhanVien.getMaNV()&amp;quot; because &amp;quot;entity&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.source.model.NhanVien.getMaNV()" because "entity" is null
at com.source.dao.NhanVienDAO.insert(NhanVienDAO.java:34)
at com.source.dao.test.NhanVienDAOTest.updateTest2(NhanVienDAOTest.java:160)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- updateTest2 -->
</testsuite> <!-- Default test -->
